### ISSUE TITLE
Filter - Thunderbird profile enhancement - exclude imapmail

### ISSUE THREAD

**Issue by stompro** [TheBestPessimist/duplicacy-utils#18]
I have always found it useful to exclude the local imap cache from the thunderbird profile, since that data is all on the imap server, the files are large, and change often.  A restore with them excluded will work fine, they will just get downloaded on the first use.

example path 
%profile%\AppData\Roaming\Thunderbird\Profiles\uulrl7mw.default\ImapMail

**Comment by TheBestPessimist** [comment]
Thanks for the suggestion.

I don't use thunderbird so I cannot test what happens when ignoring that particular folder so i crosslinked the issue on the official duplicacy forum here: https://forum.duplicacy.com/t/filters-file-should-i-exclude-thunderbird-imapmail-folder/1475.

My concern would be: what if there are accounts stored just for history/archival purposes (eg. there's no remote server). Won't they lose all the images and rest of attachments?

**Comment by TheBestPessimist** [comment]
From the discussion linked above, I chose not to mess with Thunderbird profile. There are too many use-cases and since this `filters` file should be a generic _use it anywhere_ one I'd much rather not make the user lose any data because of bad defaults.

If the user desires to exclude any particular files in the Thunderbird profile, he should do it himself and in case anything breaks/is lost then he did it on his own.

Sidenote: The usage of my filters file (along with user specific filters) will also improve considerably once @gilbertchen will include https://github.com/gilbertchen/duplicacy/pull/514.
