### ISSUE TITLE
mistake in regex?

### ISSUE THREAD

**Issue by tophee** [TheBestPessimist/duplicacy-utils#2]
Are you sure that this will work:

https://github.com/TheBestPessimist/duplicacy-utils/blob/834473e6ebb738dfdd1a45e483a4758eda488f0b/filters#L169

Shouldn't it be
~~~~
e:AppData/Local/Packages/.*
~~~~

(and likewise all the other exclusions in the same format)?

**Comment by NiJoao** [comment]
Regarding the first "/":
If you want to support selecting a users home folder it can't be there.
Otherwise it's irrelevant.

Regarding the last ".*":
See my very recent post here: https://github.com/gilbertchen/duplicacy/issues/355#issuecomment-366329381 
As per the Documentation:
> When a directory is excluded, all files and subdirectories under it will also be excluded. Therefore, to include a subdirectory, all parent directories must be explicitly included.

And keep in mind that Duplicacy uses the MatchString method, that searches for a sub-string in any position. https://golang.org/pkg/regexp/#example_MatchString

**Comment by TheBestPessimist** [comment]
**Regarding the first "/"**:
I don't think there's any reason. I just like the `/` so that is "yells" **it's only these folders!!!!!**.

**Regarding the last ".*"**
I agree with @NiJoao: there shouldn't be a need for that (at least in this case i think).

What I want to do is ignore the content of `<anyUsernameHere>/AppData/Local/Packages/.*` but anything else in `AppData` can be backed up as needed. 

I wrote (i think) in the file a comment for my reason to ignore that (and opened a bug for duplicacy here: https://github.com/gilbertchen/duplicacy/issues/309): there's some weird skype file which can't be backed up for some reason and duplicacy just stops the backup (so that no data loss occurs).

**Comment by tophee** [comment]
Thanks for both of your answers. Yes, I suspected thar the trailing `.*` is unnecessary but since the filter didn't work for me out of the box (because I was using it on a user's home directory), I was thinking about possible sources of error and those were the teo that came to mind. But I was unsure, since I know @TheBestPessimist has invested quite some thought into this. 

In any case, I now think the first slash shouldn't be there. 

As regards the MatchString method: I'm not a programmer, so if someone could explain if/how needs to be considered when composing filter rules?

**Comment by TheBestPessimist** [comment]
There's a much more detailed discussion in [#335](https://github.com/gilbertchen/duplicacy/issues/355), you could want t look there.

From that discussion i might get to change a lot of the regexes (again :D).

**Comment by TheBestPessimist** [comment]
todo: check where it would make sense to remove the first slash as per @tophee's problem
