### ISSUE TITLE
backup a network share 

### ISSUE THREAD

**Issue by pkitbox** [TheBestPessimist/duplicacy-utils#27]
Hi, i try to backup a network share but its not working with the scheduled task which was created with "create-scheduled-task-windows"

it works fine when i run the "backup.ps1" manually, but not when it runs by the scheduled task, there is no log file in 
M:\.duplicacy\tbp-logs.
There is only log file in  M:\.duplicacy\tbp-logs  when running manually

Any help appreciated 
thanks

**Comment by TheBestPessimist** [comment]
Hey @pkitbox,

You're saying
> i try to backup a network share but its not working with the scheduled task
> [...]
> it works fine when i run the "backup.ps1" manually

The fact that it works when run manually makes me think that there's some permissions issues with the scheduled task.



Just to take this out of the way: can you please run the file `create-scheduled-task-windows.bat`as administrator (right click -> `Run as Administrator`). 
I assume this is the case, can you tell me if this repository (`duplicacy-utils`) is placed inside the `.duplicacy` folder (ie. you have the file `.duplicacy/duplicacy-utils/config.user.ps1`)?

Here's a screenshot with what i mean:
![image](https://user-images.githubusercontent.com/4482210/110582611-1fd2d680-8175-11eb-9861-aa96f9420232.png)


Afterwards, please open `Task Scheduler`, goto `Task Scheduler Library`, select the (I expect) single `Duplicacy Backup for repository bla` entry there.

![image](https://user-images.githubusercontent.com/4482210/110583106-d9ca4280-8175-11eb-8c60-f25bb36b8216.png)


Add screenshots for the `General` and `Actions tabs.



What happens if you run the scheduled task manually? For how long does it run? You can see all of that if you scroll to the right in that window.

![image](https://user-images.githubusercontent.com/4482210/110583426-59581180-8176-11eb-802e-37dda41da142.png)
![image](https://user-images.githubusercontent.com/4482210/110583536-81477500-8176-11eb-8674-e8f48802f72b.png)

**Comment by pkitbox** [comment]
**Just to take this out of the way: can you please run again the file create-scheduled-task-windows.batas administrator (right click -> Run as Administrator).**  
Yes, i dit run as administrator

**I assume this is the case already, but can you tell me if duplicacy-utils is placed inside the .duplicacy folder (ie. you have the file .duplicacy/duplicacy-utils/config.user.ps1)?**
Yes, its inside there
![image](https://user-images.githubusercontent.com/80339222/110761120-a825aa00-824f-11eb-966a-ac22946e786b.png)


![image](https://user-images.githubusercontent.com/80339222/110761185-bc69a700-824f-11eb-8847-6d757594006e.png)

![image](https://user-images.githubusercontent.com/80339222/110761208-c25f8800-824f-11eb-8d6e-15f1239278ea.png)


**Part 2
What happens if you run the scheduled task manually? For how long does it run? You can see all of that if you scroll to the right in that window.**

It runs for only one second   

![image](https://user-images.githubusercontent.com/80339222/110761357-f0dd6300-824f-11eb-9ab1-820b63f92885.png)

no log files were created in .duplicacy/logs  when i run the task manually.

Only logfiles were create when i run the .ps1 script  manually from cmd console

i Think theres some kind of problem that the network share (M:) isnt connected when running it within the scheduled task
but i dont see where i can fix it.


Thank you for your help

**Comment by pkitbox** [comment]
Hi, i changed the scheduled task , so that the scheduled task starts a script which connects the Network shares and then starts the backup.ps1.
Works fine now.

thanks

**Comment by TheBestPessimist** [comment]
Interesting. So in the end, the network shares are not available when the user is logged and runs the scheduled task. 

Does this mean that the user which runs the scheduled task is not admin and different from "currently logged in user" (which has access to the network shares)?
